# Host file for APICs we want to push plays to. Variables are defined here
# but they can be defined anywhere. These are generic to protect the 
# innocent.
apic:
  hosts:
    1.2.3.4
  vars:
    username: bob
    password: cisco
    mytenant: tenant1
    myvrf: vrf1
    myap: ap1
    bdname: bd1
    myip: 10.1.1.1
    mymask: 24
    myepg: epg1