---
#
# Playbook configures a VRF under a particular Tenant. 
# This playbook assumes that the Tenant has been created
# This playbook does not include any pre/post checks.
#
- name: Configuring a new Three Tier Application
  hosts: all
  connection: local
  gather_facts: no
  
  tasks:
  - name: Create VRF
    cisco.aci.aci_vrf:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      tenant: "{{ tenant }}"
      vrf: "{{ vrf }}"
      description: "{{ desc }}"
      validate_certs: no
      state: present
